name: adrl
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - brotli-python=1.1.0=py38he333c0f_1
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.7.4=hf0a4a13_0
  - cachecontrol=0.14.0=pyhd8ed1ab_1
  - cachecontrol-with-filecache=0.14.0=pyhd8ed1ab_1
  - certifi=2024.7.4=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cleo=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py38h11842c7_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distlib=0.3.8=pyhd8ed1ab_0
  - dulwich=0.21.7=py38h336bac9_0
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.15.4=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.8=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.4=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.12.2=pyhd1c38e8_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py38h10201cd_0
  - keyring=24.3.1=py38h10201cd_0
  - krb5=1.21.3=h237132a_0
  - libblas=3.9.0=23_osxarm64_openblas
  - libcblas=3.9.0=23_osxarm64_openblas
  - libcxx=18.1.8=h3ed4263_6
  - libedit=3.1.20191231=hc8eb9b7_2
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - liblapack=3.9.0=23_osxarm64_openblas
  - libopenblas=0.3.27=openmp_h517c56d_1
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libzlib=1.3.1=hfb2fe0b_1
  - llvm-openmp=18.1.8=hde57baf_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - more-itertools=10.4.0=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py38h4b8c310_0
  - ncurses=6.5=h7bae524_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.24.4=py38ha84db1f_0
  - openssl=3.3.1=h8359307_3
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyhd8ed1ab_0
  - pkginfo=1.11.1=pyhd8ed1ab_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - poetry=1.8.3=osx_pyh534df25_1
  - poetry-core=1.9.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.8.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - psutil=6.0.0=py38h3237794_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyproject_hooks=1.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.19=h2469fbe_0_cpython
  - python-build=1.2.1=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python_abi=3.8=5_cp38
  - pyzmq=26.2.0=py38h7e0d939_0
  - rapidfuzz=3.9.6=py38h11842c7_0
  - readline=8.2=h92ec313_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.13.2=pyha770c72_0
  - tornado=6.4.1=py38h3237794_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trove-classifiers=2024.7.2=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - virtualenv=20.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xattr=1.1.0=py38h336bac9_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.5=hcc0f68c_4
  - zipp=3.20.1=pyhd8ed1ab_0
  - zstandard=0.23.0=py38h43bb1b3_0
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - absl-py==2.1.0
      - aiosignal==1.3.1
      - attrs==24.2.0
      - cachetools==5.5.0
      - cffi==1.16.0
      - chex==0.1.7
      - click==8.1.7
      - cloudpickle==3.0.0
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.37
      - d3rlpy==2.6.0
      - d4rl==1.1
      - dataclasses-json==0.6.7
      - dm-control==1.0.20
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.3.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - flatbuffers==2.0.7
      - flax==0.3.5
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - google-api-core==2.19.2
      - google-auth==2.34.0
      - google-auth-oauthlib==1.0.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - h5py==3.11.0
      - imageio==2.35.1
      - jax==0.4.11
      - jaxlib==0.4.11
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - labmaze==1.0.6
      - llvmlite==0.41.1
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - matplotlib==3.5.3
      - mdurl==0.1.2
      - minari==0.4.3
      - mjrl==1.0.0
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mujoco==3.1.6
      - mujoco-py==2.1.2.14
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numba==0.58.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optax==0.0.6
      - orjson==3.10.7
      - pandas==2.0.3
      - pettingzoo==1.24.3
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - portion==2.4.2
      - proto-plus==1.24.0
      - protobuf==5.27.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pybullet==3.2.6
      - pygame==2.6.0
      - pyopengl==3.1.7
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2024.1
      - pyyaml==6.0.2
      - ray==2.9.1
      - referencing==0.35.1
      - requests-oauthlib==2.0.0
      - rich==13.8.0
      - rpds-py==0.20.0
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - setuptools==74.1.1
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - structlog==24.4.0
      - sympy==1.13.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensordict==0.5.0
      - tensorflow-probability==0.21.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tianshou==0.5.1
      - toolz==0.12.1
      - torch==2.4.0
      - torchrl==0.2.1
      - torchviz==0.0.2
      - tqdm==4.66.5
      - typer==0.12.5
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - wandb==0.17.7
      - werkzeug==3.0.4
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/cql
